### ISSUE TITLE
'Per-project installation' and Qt Creator

### ISSUE THREAD

**Issue by benlau** [lirios/fluid#103] opened 2017-05-17 17:45 UTC
Hello,

If a user uses Fluid according to the instruction of 'Per-project installation' method, it would work, but Qt Creator will not be able to recognise Fluid and it will show a red line under the import statement. And syntax auto-completion will not works.

That is because the QML_IMPORT_PATH is not set, and the file structure does not match with Qt's way. 

Basically, Qt Creator does not parse QML files in Qt resources. It will only parse files in file system. 

The expected way to place files should be: 

```
.
└── Fluid
    ├── Controls
    │   ├── Action.qml
    │   ├── AlertDialog.qml
    │   ├── AppBar.qml
```

But currently,  Fluid place its source in this way:

develop branch
```
.
├── src
│   ├── imports
│   │   ├── controls
│   │   │   ├── Action.qml
│   │   │   ├── AlertDialog.qml
│   │   │   ├── AppBar.qml
```

Therefore, it is impossible for Qt Creator to recognise it.

master branch
```
.
├── controls
│   ├── Action.qml
│   ├── AlertDialog.qml
│   ├── AppBar.qml
```

It is better, but the root parent folder is not named as `Fluid` and the case of `controls` do not match with the package name (It should be `Controls`)

So to fix this problem, it just needs to move files according to the expected way, but of coz that probably will break the current build script.

I have few questions

1) Why the file structure of master branch and develop branch is different?

2) Any chance to change the file structure in a way that Qt Creator is able to handle? I know that it may be huge changes, if there has no special concern, I may try to contribute.

Thanks.

**Comment by plfiorini** [comment] 2017-05-17 19:09
Source tree was restructured to look more like Qt repositories since it's a convention I like.
It is completely irrelevant to the QtCreator issue and the previous structure had basically the same issue.

First let's identify all the use cases:

1. system-wide installation, mostly used to build Linux packages
2. per-project build where QML and icons are embedded into the resources and plugins are statically built into the application
3. dynamic build where you build Fluid and don't install it

The root cause is that QML files are embedded into the resource and Qt Creator is unable to see those files.

I think this problem can be resolved as follows (basically merge 2 and 3 together):

1. Copy all QML files and icons to the build directory and set QML_IMPORT_PATH to $$FLUID_BUILD_DIR/qml (already did in a84b380a1fedda6cb02b1ba054242ded35286be5)
2. Stop embedding QML and icons into the resources
3. Now Fluid modules will live with the app binaries and won't need to be installed system wide though it requires the build directory to be seen from $QML2_IMPORT_PATH environment variable.

This has also the added benefit of simplifying per-project builds, users will not need to manually create image providers and the setup will be very quick.

So that will work in theory let's find out in practice.

**Comment by oKcerG** [comment] 2017-05-18 07:39
The image providers will be automatically registered or won't be needed anymore ?

Btw, I don't think the root cause is because they are embedded. With a file hierarchy like proposed by benlau, it can work with qrc or not.

**Comment by plfiorini** [comment] 2017-05-18 08:20
The image providers will be automatically registered as it happens with any normal QML plugin.

And yes the root cause is because QtCreator cannot reach files in the resources, I'm not going to change the source tree layout just because of QtCreator limitations.

And I don't understand why statically linking QML plugins into the application binary is needed at all.
What I'm talking about is copying all QML plugins and QML files into the build directory where QtCreator can reach them.

**Comment by oKcerG** [comment] 2017-05-18 09:00
The advantage of statically linking is that you don't have to build a plugin beforehand for each platform you are targeting.

**Comment by plfiorini** [comment] 2017-05-18 09:02
You still need to build the code for each platform, there's no difference.

**Comment by oKcerG** [comment] 2017-05-18 09:13
Static linking workflow:

- include fluid.pri in .pro
- add import path and register image providers in main.cpp
- Compile app and deploy to any platform

Plugin Workflow:
- Compile plugin and make sure it is deployed to the app executable directory.
- Compile app and deploy to plaforms you compiled the plugin for

Please correct me if I made any mistakes.
Maybe the first step of the plugin workflow could be made automatically in a .pri file ?

**Comment by plfiorini** [comment] 2017-05-18 12:04
Yes in the .pri file I plan to add rules to build the plugins

**Comment by oKcerG** [comment] 2017-05-18 12:10
👍  that's fine for me then if it's possible to just include the .pri and not having to do anything else.

**Comment by benlau** [comment] 2017-05-20 21:33
hi @plfiorini,

Thank for your reply. But I am quite confused with your solution of plugin work flow. Do user still need to perform a manual build per platform? Things like running a `make install` on Fluid for desktop / Android / iOS ? 

When we are using a package from qpm, it will fetch C++ source in a local folder and build and link statically. So that it don't need a manual build of individual library per platform. I am not sure is the plugin work flow did the same mechanism?

**Comment by plfiorini** [comment] 2017-05-20 21:49
I'm not familiar with qpm but the idea is that you:

1. Clone the fluid repository inside your source tree
2. Include the relevant .pri file in your project
3. Build your application

All Fluid QML plugins will be built as if they were part of your project.

**Comment by plfiorini** [comment] 2017-05-22 21:01
After 2 weeks of qbs I forgot how poor is qmake

**Comment by plfiorini** [comment] 2017-05-22 22:21
With Qbs it's as easy as this example: https://github.com/lirios/fluid-examples

QtCreator sees the imports, no need to modify your code except for very few minor details in your .qbs files, no system-wide installation, no static linking.

Working with qmake to achieve this feels like a lot of work, if not impossible (at least in the way I thought), with the only benefit of making QtCreator see the imports...

**Comment by plfiorini** [comment] 2017-05-22 22:29
If you are making a new project I strongly suggest to abandon qmake and use qbs, it's so much easier to work with, doesn't generate make files which means it takes care of the build graph itself, low cost setup even for complex use-cases.

This issue has been taken care of with qbs, so if you are in a position to use qbs, please do so and tell me if there is something I need to do there.

Regarding qmake I don't think I can make QtCreator see the imports so easily as I thought.

**Comment by rmallah** [comment] 2017-05-23 08:29
will using qbs also solve the problem of Qt designer not being able to use Fluid controls?

**Comment by benlau** [comment] 2017-05-23 17:59
@plfiorini hmmm.. What if I propose an alternative solution? Since you have a installation script that install *.qml to a build folder , I think it could just make it to copy *.h / *.cpp plus a special fluid.pri to that folder too.

So that it could create a installation package which is static build and Qt creator friendly.

**Comment by plfiorini** [comment] 2017-05-23 18:15
@benlau i don't get it sounds exactly what you have now, and i don't have any script that copy *.qml to the build folder. qmake does when you build fluid.pro

**Comment by benlau** [comment] 2017-05-23 18:22
@plfiorini Isn't this commit https://github.com/lirios/fluid/commit/a84b380a1fedda6cb02b1ba054242ded35286be5 copy *.qml to the build folder?

**Comment by plfiorini** [comment] 2017-05-24 06:51
@rmallah No that is a separate issue #86 which will be implemented after 1.0

**Comment by rmallah** [comment] 2017-05-24 08:09
thanks @plfiorini   , 

If possible please tell one "work flow" that works now ,   by which i  can use Fluid 
with below functions

(1) Auto complete/ Hinting of methods / properties  of Fluid components works in QtCreator editor.
(2) Able to preview my works that Uses Fluid Controls in QtCreator Designer.

I am already using it in my new project and having a difficult time due to non cooperation
from QtCreator.

regds
mallah.

**Comment by rmallah** [comment] 2017-05-24 17:13
Ok finally got my environment in a working state with fluid.

I used `CONFIG+=install_under_qt to install plugins and QML modules inside Qt` 
as described under   `System-wide installation`

The rough steps are:
(1)  git clone https://github.com/lirios/fluid 
(2) cd fluid
(3) git submodule update --init  
(4) mkdir build 
(5) cd build
(6) /path/to/qmake  LIRI_INSTALL_PREFIX=/opt/liri   CONFIG+=install_under_qt      ../fluid.pro
(5) make
(6) make install

the above will install fluid along with Qt inbuilt imports

for android version of qmake
(1)  git clone https://github.com/lirios/fluid  fluid-android
(2) cd fluid-android
(3) git submodule update --init  
(4) mkdir build 
(5) cd build
(6)  /path/to/android_armv7/bin/qmake  LIRI_INSTALL_PREFIX=/opt/liri-android    CONFIG+=install_under_qt      ../fluid.pro
(5) make
(6) make install

@plfiorini  its the same steps that is already there , just elaborated it , pls feel free to remove
unnecessary steps.

**Comment by rmallah** [comment] 2017-05-24 17:15
Workaround Report:

below line prevented the QtCreator designer in displaying the QML file properly
 
`import Fluid.Controls 1.0 as FluidControls`

replace above with 

`import Fluid.Controls 1.0`

But in that case the prefix FluidControls needs to be dropped

eg : `FluidControls.BodyLabel` needs to be written as only `BodyLabel`

**Comment by plfiorini** [comment] 2017-09-24 15:35
Seems like one need to include `fluid.pro` as subdir

**Comment by plfiorini** [comment] 2017-09-24 15:45
@rmallah some developers prefer not to rebuild Fluid every time they update Qt and a system-wide installation can leave files around

Building along with the app is often better.

**Comment by plfiorini** [comment] 2017-09-24 19:47
A non static build with `.pri` files seems impossible but Fluid can be used as a subdir.

PR coming soon.

**Comment by plfiorini** [comment] 2017-09-24 20:08
@benlau See PR https://github.com/lirios/fluid/pull/150

Also @oKcerG

**Comment by plfiorini** [comment] 2017-09-29 21:18
Patch merged

**Closed by plfiorini** 2017-09-29 21:18 UTC
Labels: enhancement

**Comment by rmallah** [comment] 2017-11-09 12:13
I am still having to use qmake . Thanks for the example minimalqmake but i feel it does
not work. The fluid project  and the actual project in subdir say "src" is being built, 

however on runtime the QML engine is not able to log the Fluid.* modules

```
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
qrc:/main.qml:5 module "Fluid.Effects" is not installed
qrc:/main.qml:4 module "Fluid.Controls" is not installed
qrc:/main.qml:5 module "Fluid.Effects" is not installed
qrc:/main.qml:4 module "Fluid.Controls" is not installed

```

I see the below in src.pro 

```
# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH = $$OUT_PWD/../fluid/qml
```
but somehow  it is being left out.

to reproduce it , simply 
copied minimalqmake in a new directory , used  QtCreator to open
minimalqmake.pro and hit build and then run.

it gives error in runtime and the app screen does not open.
am I missing anything ?

using : Qt 5.9.2 + Qt Creator: 4.4.1

**Comment by plfiorini** [comment] 2017-11-13 18:06
@rmallah Did you clone fluid inside the `minimalqmake` directory?

**Comment by plfiorini** [comment] 2017-11-13 18:09
@rmallah If you did then the problem could be the `QML2_IMPORT_PATH` environment variable that should contain the build directory because the QML plugins are not installed systemd-wide. I didn't think about it because the per-project installation is mainly designed for Android where `src.pro` has `ANDROID_EXTRA_PLUGINS` set.

**Comment by rmallah** [comment] 2017-11-14 01:03
Hi Pier , Yes fluid is cloned inside minimalqmake

```
user01@mallahlaptop:/mnt/khajana/Qt/Projects/minimalqmake$ cat minimalqmake.pro
TEMPLATE = subdirs

SUBDIRS += fluid src

user01@mallahlaptop:/mnt/khajana/Qt/Projects/minimalqmake$ tree -f  -L 2 .
.
├── ./fluid
│   ├── ./fluid/AUTHORS.md
│   ├── ./fluid/CONTRIBUTING.md
│   ├── ./fluid/doc
│   ├── ./fluid/examples
│   ├── ./fluid/fluid.pro
│   ├── ./fluid/fluid.pro.user
│   ├── ./fluid/fluid.qbs
│   ├── ./fluid/icons
│   ├── ./fluid/LICENSE.MPL2
│   ├── ./fluid/qbs
│   ├── ./fluid/README.md
│   ├── ./fluid/scripts
│   ├── ./fluid/src
│   └── ./fluid/tests
├── ./minimalqmake.pro
├── ./minimalqmake.pro.user
├── ./README.md
└── ./src
    ├── ./src/main.cpp
    ├── ./src/main.qml
    ├── ./src/Page1Form.ui.qml
    ├── ./src/Page1.qml
    ├── ./src/qml.qrc
    ├── ./src/qtquickcontrols2.conf
    └── ./src/src.pro

9 directories, 17 files

```
Initial Part of  src.pro

```
TEMPLATE = app

QT += qml quick quickcontrols2

CONFIG += c++11

SOURCES += main.cpp

RESOURCES += qml.qrc

# Additional import path used to resolve QML modules in Qt Creator's code model
#QML_IMPORT_PATH = $$OUT_PWD/../fluid/qml
QML2_IMPORT_PATH = $$OUT_PWD/../fluid/qml

```

I still have the same problem

```
Starting /mnt/khajana/Qt/Projects/build-minimalqmake-Desktop_Qt_5_9_2_GCC_64bit-Debug/src/src...
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
qrc:/main.qml:5 module "Fluid.Effects" is not installed
qrc:/main.qml:4 module "Fluid.Controls" is not installed
qrc:/main.qml:5 module "Fluid.Effects" is not installed
qrc:/main.qml:4 module "Fluid.Controls" is not installed

```

**Comment by SushiTee** [comment] 2017-11-18 17:29
I got the same problem.

**Comment by edips** [comment] 2017-11-20 22:22
Using qrc didn't work for me for desktop. qmake worked for desktop and Android according to @tim-sueberkrueb's suggestion for android.

```
git clone https://github.com/lirios/fluid.git
cd fluid
mkdir build && cd build
/home/[username]/Qt5.9.2/5.9.2/gcc_64/bin/qmake ../fluid.pro CONFIG+=install_under_qt
make
sudo make install
```
Because it used `sudo make install` root permissions should be disabled for `"/home/[username]/Qt5.9.2/5.9.2/gcc_64/qml/Fluid`" folder. To do this: `sudo chown -R [username]:[username] ./Folder` I never recommend `sudo chown -R [username]:[username] ./Fluid` command if your Linux distro is different from Ubuntu.
Tested on Ubuntu 16.04

**Comment by rmallah** [comment] 2017-11-21 05:51
i think CONFIG+=install_under_qt   is not a good thing to do. It is rigid and brittle , 
per project installations are flexible but lately could not get it to work properly.
as already indicated in older comments i am having to use qmake build system.

**Comment by fro0m** [comment] 2017-11-23 04:42
same problem

`QQmlApplicationEngine failed to load component
qrc:/main.qml:4 module "Fluid.Controls" is not installed
qrc:/main.qml:5 module "Fluid.Effects" is not installed
qrc:/main.qml:4 module "Fluid.Controls" is not installed
qrc:/main.qml:5 module "Fluid.Effects" is not installed`

I tried minimalqmake

**Comment by rmallah** [comment] 2017-11-23 05:32
@plfiorini  Hi Pier , Please give some time for this issue. I am not able to use the 
latest fluid in my projects i am able to use only the older versions.

**Comment by rmallah** [comment] 2017-12-03 16:11
@plfiorini , Hi Pier   can you please see 
https://github.com/rmallah/fluid/commit/931ab34f650a4c98714d91698c54e7af97eb42d3
it seems to be fixing the problem. 
Thanks & Regards. mallah.

**Comment by rmallah** [comment] 2017-12-04 02:30
pls consider 
https://github.com/rmallah/fluid/commit/9205b8281031ab921ca41b18e5780719702123b3

**Comment by motters** [comment] 2018-02-14 16:18
For anyone struggling with the issue "Fluid.Controls is not installed" etc; i found the solution lying in the development branch. Add the following to you src.pro file if using the master branch.

```qmake
macx {
    # Bundle Fluid QML plugins with the application
    APP_QML_FILES.files = $$OUT_PWD/../fluid/qml/Fluid
    APP_QML_FILES.path = Contents/MacOS
    QMAKE_BUNDLE_DATA += APP_QML_FILES
}

win32 {
    WINDEPLOYQT_OPTIONS = -qmldir $$OUT_PWD/../fluid/qml/Fluid
}
```

**Comment by eswizardry** [comment] 2019-02-16 13:50
The latest master branch still needs the workaround to run "minimalqmake" example.

[rmallah@9205b82](https://github.com/rmallah/fluid/commit/9205b8281031ab921ca41b18e5780719702123b3)
> qputenv("QML2_IMPORT_PATH", "../fluid/qml");

**Comment by trungnd95** [comment] 2019-02-28 03:26
Hi @rmallah,
Iam trying to integrate Fluild plugin in my own project. But when I did exactly as instruction https://liri.io/docs/sdk/fluid/develop/deployment.html, I faced with some problems and I wonder that: 
1. Do we have to build minimalqmake.pro project that contains 2 subs dir: fluild and src OR we only build src folder with src.pro file? 
2. If I only build src folder, it lead to the problem of Fluild has not installed yet. If I build big project that has minimalqmake.pro file, It lead to the problem like that: 
```C++
error: unrecognized command line option ‘-Wshift-overflow=2’
error: unrecognized command line option ‘-Wduplicated-cond’
```
Do you have any suggestions for building successfully?

**Comment by plfiorini** [comment] 2019-04-27 09:04
@trungnd95 Build `minimalqmake.pro`. You usually build to root project and it's not different with Fluid.
