### ISSUE TITLE
CMake error on Ubuntu 19.04, CMake 3.13.4

### ISSUE THREAD

**Issue by timosachsenberg** [lirios/fluid#290] opened 2019-07-15 08:35 UTC
Hi,
Ubuntu 19.04, CMake 3.13.4, Qt 5.12
I am happy to provide more information if needed.

After installing all dependencies I currently get a:

CMake Error at cmake/shared/modules/LiriBuild.cmake:97 (message):
  Unknown arguments were passed to liri_add_executable (OFF).
Call Stack (most recent call first):
  cmake/shared/modules/LiriAddExecutable.cmake:34 (_liri_parse_all_arguments)
  src/demo/CMakeLists.txt:7 (liri_add_executable)
-- Configuring incomplete, errors occurred!

**Comment by plfiorini** [comment] 2020-04-16 21:53
Tested with a slightly updated system and cannot reproduce: Ubuntu 19.10, Qt 5.14, still CMake 3.13

**Comment by plfiorini** [comment] 2020-04-17 06:40
With commit fee08d610f8b1447de1c3f3fe65f1dbdf7bfa823, the `cmake/shared/` submodule was updated fixing the issue so this is fixed now.

**Closed by plfiorini** 2020-04-17 06:40 UTC
Labels: bug, platform/linux
