### ISSUE TITLE
DateTimePicker crashes once instantiated with Qt 5.12

### ISSUE THREAD

**Issue by obeezzy** [lirios/fluid#276] opened 2019-01-11 06:18 UTC
## Expected Behavior
The app should not crash when I instantiate DateTimePicker.
## Current Behavior
The app crashes every time I instantiate DateTimePicker. This component worked perfectly with Qt 5.10.

## Possible Solution

It seems to be a binding loop, because Qt Creator reports that the app crashes on **line 247** of **datetimepicker.cpp**.

## Steps to Reproduce (for bugs only)

1. Create an app with an instance of DateTimePicker.
2. Watch the app crashes instantly.

## Context

I want to select a date and time.

## Environment

* Qt 5.12
* Ubuntu 16.04
* Desktop
* i5, 8GB RAM, 1080p screen

**Comment by plfiorini** [comment] 2019-01-11 10:02
Can you please paste a working snippet of your code to reproduce the crash?

**Comment by obeezzy** [comment] 2019-01-12 12:01
It crashed at the last line of this function:
```cpp
void DateTimePicker::setSelectedDateTime(const QDateTime &dateTime)
{
    if (m_selectedDateTime == dateTime)
        return;

    m_selectedDateTime = dateTime;
    Q_EMIT selectedDateTimeChanged();
}
```

**Comment by luntik2012** [comment] 2019-04-09 07:34
Did you connected that signal from c++ or used `onSelectedDateTimeChanged` or bound `selectedDateTime:` in qml?

> It seems to be a binding loop

There is a check in the beginning of `setSelectedDateTime` to avoid binding loop:

```c++
if (m_selectedDateTime == dateTime)
        return;
```

Could you provide minimal example?

**Comment by plfiorini** [comment] 2019-04-27 09:18
Can't reproduce. My system has Qt 5.12.3 and I have now modified `fluid-demo` with a `onSelectedDateTimeChanged` handler and it doesn't crash.

**Comment by plfiorini** [comment] 2019-04-27 09:20
Closing down the issue because it cannot be reproduced, and no minimal example was provided.

**Closed by plfiorini** 2019-04-27 09:20 UTC
Labels: bug, needs info
