### ISSUE TITLE
Cannot run fluid demo in Qt 5.9.3 on Ubuntu 17.04

### ISSUE THREAD

**Issue by batthegh** [lirios/fluid#167] opened 2017-11-27 18:08 UTC
Hi,
I opened the fluid.qbs as instructed on the fluid web page:

"Open up fluid.qbs with QtCreator, hit build and run to see the demo in action."

but I'm getting the following message in Qt Creator:

"Could not find the executable, please specify one."

Could you please help me out to get the demo working?

Thanks!

**Comment by edips** [comment] 2017-11-29 21:19
Hi. You should install fluid according to Qt5's installation path.
```
cd fluid
git submodule update --init --recursive
/home/[user name]/Qt5.9.2/Tools/QtCreator/bin/qbs setup-toolchains --type gcc /usr/bin/g++ gcc
/home/[user name]/Qt5.9.2/Tools/QtCreator/bin/qbs setup-qt /home/[user name]/Qt5.9.2/5.9.2/gcc_64/bin/qmake qt5
/home/[user name]/Qt5.9.2/Tools/QtCreator/bin/qbs config profiles.qt5.baseProfile gcc
/home/[user name]/Qt5.9.2/Tools/QtCreator/bin/qbs -d build profile:qt5 
```
Now demo is ready to run:
`/home/[user name]/Qt5.9.2/Tools/QtCreator/bin/qbs run --no-build -d build --products fluid-demo`

**Comment by plfiorini** [comment] 2017-12-11 17:57
@batthegh Is your QtCreator from Ubuntu or the Qt binaries.

What @edips wrote should work but if you use QtCreator from the Qt binaries you should be able to build from the IDE.

**Comment by luntik2012** [comment] 2017-12-13 08:31
cannot reproduce it now, changed distro. close this please

**Closed** 2017-12-13 09:14 UTC
Labels: needs info
