### ISSUE TITLE
QQmlExpression: Expression depends on non-NOTIFYable properties: QQuickIconLabel::color

### ISSUE THREAD

**Issue by luntik2012** [lirios/fluid#177] opened 2017-12-19 09:06 UTC
QQmlExpression: Expression file:///usr/lib/qt/qml/Fluid/Controls/TabbedPage.qml:171:36 depends on non-NOTIFYable properties:
    QQuickIconLabel::color
QQmlExpression: Expression file:///usr/lib/qt/qml/Fluid/Controls/TabbedPage.qml:160:32 depends on non-NOTIFYable properties:
    QQuickIconLabel::color
QQmlExpression: Expression file:///usr/lib/qt/qml/Fluid/Controls/TabbedPage.qml:171:36 depends on non-NOTIFYable properties:
    QQuickIconLabel::color
QQmlExpression: Expression file:///usr/lib/qt/qml/Fluid/Controls/TabbedPage.qml:160:32 depends on non-NOTIFYable properties:
    QQuickIconLabel::color

Tell me if you need code snippets to reproduce this.
Used this fluid https://aur.archlinux.org/packages/fluid-git/
UPD. the same with current git version

**Comment by plfiorini** [comment] 2017-12-19 11:08
This is caused by Qt Quick Controls 2 new changes.
I have a branch that is going to be merged in the new feature.

**Comment by plfiorini** [comment] 2017-12-20 09:16
Fixed

**Closed by plfiorini** 2017-12-20 09:16 UTC
Labels: bug, upstream

**Comment by blok1118** [comment] 2020-12-06 22:10
Hello. How to fix in old version (don't know version number) without updating?

**Comment by plfiorini** [comment] 2020-12-07 08:46
You are required to use at least Qt 5.10, consider that the latest version is 5.15.
